version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - 3000:3000
    environment:
      - PORT=3000
  client:
    build:
      context: ./client
    ports:
      - 80:80
    environment:
      - GRAPHQL_API_URL=http://localhost:3000/graphql
    depends_on:
      - server


